### ISSUE TITLE
status display for progress-false does not match the full display:

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/tailpipe#210]
**full output**
```
Collecting logs for my_dynamic_log.test from 2025-02-11 (initial collection, default 7 days)

Artifacts:
  Discovered: 1 
  Downloaded: 1 12kB
  Extracted:  1 

Rows:
  Received: 100 
  Enriched: 100 
  Saved:      0 
  Filtered: 100 

Files:
  No files to compact.

Completed: 347ms
```

**progress = false**
```
Artifacts discovered: 1. Artifacts downloaded: 1. Artifacts extracted: 1. Rows enriched: 100. Rows converted: 0. Errors: 0.
```

should be something like 

```
Artifacts discovered: 1. Artifacts downloaded: 1. Artifacts extracted: 1. Rows enriched: 100. Rows saved: 0. Rows filtered: 100  Errors: 0.
```

and possibly also include the time?
(don't think we need received?)
