### ISSUE TITLE
Show more progress info during compaction?

### ISSUE THREAD

**Issue by e-gineer** [turbot/tailpipe#241]
Collecting cloudtrail logs feels great ... until you hit compaction phase. I spent a couple of minutes in there with very little output, in fact I thought it was stuck at one point.

```
nathan@e-gineer-Mac-2024 experiments % tailpipe collect aws_cloudtrail_log.saas_prod_useast2

Collecting logs for aws_cloudtrail_log.saas_prod_useast2 from 2025-03-05 (initial collection, default 7 days)

Artifacts:
  Discovered: 5,620
  Downloaded: 5,620 1.5GB
  Extracted:  5,620

Rows:
  Received: 10,446,985
  Enriched: 10,446,985
  Saved:    10,446,985

Files:
  Compacted: 1083 => 8

Completed: 3m27s
```

For discovered and downloaded there is a sense of progress through the filename and the data size. Could we offer a similar insight into progress in the compaction line? e.g. could we show the source file currently being added to the compaction? Give me a sense that it's working hard.

I know from the CPU it's working hard (1000% <grin>), but it's hard to tell from the UI.
